-- ============================================================
-- MTRTS — Media Technology Repair Tracker System
-- Database Schema: Asset & Configuration Management
-- Module 2: Asset Management
-- ============================================================
-- Run users_schema.sql FIRST before running this file.
-- This file depends on the users table already existing.
-- ============================================================


-- ------------------------------------------------------------
-- TABLE 1: asset_categories
-- Dynamic — IT staff can add and edit categories.
-- Referenced by: assets.category_id
-- ------------------------------------------------------------
CREATE TABLE asset_categories (
  category_id     INT           PRIMARY KEY AUTO_INCREMENT,
  category_name   VARCHAR(100)  NOT NULL UNIQUE,
    -- e.g. 'Projector', 'Sound System', 'AV Switcher',
    --      'Display', 'Microphone', 'AV Rack'
  has_bulb_hours  TINYINT(1)    NOT NULL DEFAULT 0,
    -- 1 = this category tracks bulb hours (e.g. Projectors)
    -- 0 = bulb hours not applicable
  description     VARCHAR(255)  NULL,
  created_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP
                                ON UPDATE CURRENT_TIMESTAMP
);

-- Seed: common AV/media equipment categories
INSERT INTO asset_categories (category_name, has_bulb_hours) VALUES
  ('Projector',    1),  -- tracks bulb hours
  ('Sound System', 0),
  ('AV Switcher',  0),
  ('Display',      0),
  ('Microphone',   0),
  ('AV Rack',      0),
  ('Camera',       0),
  ('Amplifier',    0);


-- ------------------------------------------------------------
-- TABLE 2: locations
-- One row per unique room in the institution.
-- Combination of building + floor + room must be unique.
-- Referenced by: assets.location_id
-- ------------------------------------------------------------
CREATE TABLE locations (
  location_id   INT           PRIMARY KEY AUTO_INCREMENT,
  building      VARCHAR(100)  NOT NULL,
    -- e.g. 'Main Building', 'Science Hall', 'Annex'
  floor         VARCHAR(50)   NOT NULL,
    -- e.g. 'Ground Floor', '1st Floor', '2nd Floor'
  room          VARCHAR(100)  NOT NULL,
    -- e.g. 'Room 101', 'Media Lab A', 'Auditorium'
  created_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE (building, floor, room)
    -- Prevents duplicate location entries.
    -- Same room cannot be registered twice.
);

-- Seed: sample locations
INSERT INTO locations (building, floor, room) VALUES
  ('Main Building', '1st Floor',    'Room 101'),
  ('Main Building', '1st Floor',    'Room 102'),
  ('Main Building', '2nd Floor',    'Room 201'),
  ('Main Building', '2nd Floor',    'Media Lab A'),
  ('Science Hall',  'Ground Floor', 'Auditorium'),
  ('Science Hall',  '2nd Floor',    'Room 204'),
  ('Annex',         '1st Floor',    'Library');


-- ------------------------------------------------------------
-- TABLE 3: assets
-- The main asset registry. Every piece of equipment lives here.
-- References: asset_categories, locations, users
-- Self-references: parent_asset_id (parent-child relationship)
-- ------------------------------------------------------------
CREATE TABLE assets (
  asset_id        INT           PRIMARY KEY AUTO_INCREMENT,

  -- Identification
  asset_tag       VARCHAR(50)   NOT NULL UNIQUE,
    -- Must be unique across all assets.
    -- e.g. 'PRJ-4022-X', 'SND-1190-B'
    -- Generated by the system or manually entered.
  serial_number   VARCHAR(100)  NULL,
    -- Unique per manufacturer. Enforced at application layer:
    -- no two assets from the same manufacturer share a serial.
  manufacturer    VARCHAR(100)  NOT NULL,
  model           VARCHAR(100)  NOT NULL,

  -- Classification
  category_id     INT           NOT NULL,
  FOREIGN KEY (category_id)
    REFERENCES asset_categories(category_id),

  -- Status
  status          ENUM('active','spare','retired') NOT NULL DEFAULT 'active',
    -- Business rule: cannot set to 'retired' if open tickets exist.
    -- Enforced at application layer, not database layer.
    -- Asset location must be assigned before status can be 'active'.

  -- Location
  location_id     INT           NULL,
    -- NULL allowed during initial onboarding only.
    -- Must be set before status can be set to 'active'.
  FOREIGN KEY (location_id)
    REFERENCES locations(location_id),

  -- Parent-Child Relationship
  parent_asset_id INT           NULL,
    -- NULL = this is a top-level asset (e.g. AV Rack)
    -- Set to another asset_id = this is a child asset
    --   e.g. a lamp or remote that belongs to a projector.
    -- Cannot reference itself. Enforced at application layer.
    -- Child assets inherit parent location by default
    --   but can be overridden via location_id above.
  FOREIGN KEY (parent_asset_id)
    REFERENCES assets(asset_id),

  -- Technical Details
  install_date    DATE          NOT NULL,
    -- Cannot be a future date. Enforced at application layer.
  firmware_version VARCHAR(50)  NULL,
  network_info    VARCHAR(100)  NULL,
    -- IP address, MAC address, or both. Free text.
  bulb_hours INT UNSIGNED NULL ,
    -- Only applicable when category has_bulb_hours = 1.
    -- NULL for all other categories.
    -- Enforced at application layer.

  -- Ownership & Department
  department_id   INT           NULL,
    -- Which department is financially responsible for this asset.
    -- FK to departments.department_id (defined in users.sql).
  FOREIGN KEY (department_id)
    REFERENCES departments(department_id),
  owner_id        INT           NULL,
    -- The user responsible for this asset.
  FOREIGN KEY (owner_id)
    REFERENCES users(user_id),

  -- QR Code
  qr_code_path    VARCHAR(255)  NULL,
    -- File path to the generated QR code image.
    -- Generated when asset is first tagged.

  -- Audit
  created_by      INT           NULL,
    -- user_id of the staff who created this record.
  FOREIGN KEY (created_by)
    REFERENCES users(user_id),
  created_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP
                                ON UPDATE CURRENT_TIMESTAMP
);


-- ------------------------------------------------------------
-- TABLE 4: asset_warranty
-- Warranty and contract details per asset.
-- Separate from assets because warranty info changes
-- independently of the physical asset record.
-- References: assets
-- ------------------------------------------------------------
CREATE TABLE asset_warranty (
  warranty_id       INT           PRIMARY KEY AUTO_INCREMENT,
  asset_id          INT           NOT NULL UNIQUE,
    -- One warranty record per asset.
  FOREIGN KEY (asset_id)
    REFERENCES assets(asset_id),

  -- Dates
  warranty_start    DATE          NOT NULL,
    -- Must be >= assets.install_date.
    -- Enforced at application layer.
  warranty_end      DATE          NOT NULL,
    -- Must be > warranty_start.
    -- Enforced at application layer.

  -- Coverage
  coverage_type     ENUM('parts','labor','parts_and_labor','onsite') NOT NULL,
  vendor_name       VARCHAR(150)  NULL,
    -- e.g. 'Epson Philippines'
  contract_reference VARCHAR(100) NULL,
    -- e.g. 'EP-2022-1104'

  -- Alerts
  -- Automated alerts are sent at 60, 30, and 7 days before
  -- warranty_end. Logic handled at application layer.
  -- No extra columns needed here for alerts.

  -- Audit
  created_at        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP
                                  ON UPDATE CURRENT_TIMESTAMP
);


-- ------------------------------------------------------------
-- TABLE 5: asset_documents
-- Files attached to an asset record.
-- Full version history — old files are never overwritten.
-- Every upload creates a new row with an incremented version.
-- References: assets, users
-- ------------------------------------------------------------
CREATE TABLE asset_documents (
  document_id     INT           PRIMARY KEY AUTO_INCREMENT,
  asset_id        INT           NOT NULL,
  FOREIGN KEY (asset_id)
    REFERENCES assets(asset_id),

  -- File Info
  document_name   VARCHAR(255)  NOT NULL,
    -- Original filename as uploaded.
    -- e.g. 'EB-2250U_User_Manual.pdf'
  file_path       VARCHAR(500)  NOT NULL,
    -- Stored path on the server under public/uploads/
    -- e.g. 'public/uploads/assets/12/manuals/v2_manual.pdf'
  file_type       VARCHAR(10)   NOT NULL,
    -- Extension only. Allowed: pdf, jpg, jpeg, png, dwg, zip
    -- Enforced at application layer.
  file_size_kb    INT           NOT NULL,
    -- File size in kilobytes.
    -- Max 50MB (51200 KB). Enforced at application layer.
  document_type   VARCHAR(50)   NULL,
    -- e.g. 'Manual', 'Wiring Diagram', 'Config Backup', 'Photo'

  -- Versioning
  version         INT           NOT NULL DEFAULT 1,
    -- Incremented on every new upload of the same document.
    -- Never overwrite — always INSERT a new row.
    -- The latest version = highest version number for that asset
    --   and document_name combination.
  is_latest       TINYINT(1)    NOT NULL DEFAULT 1,
    -- 1 = this is the current version
    -- 0 = this is an older version (superseded)
    -- When a new version is uploaded, set previous is_latest = 0.

  -- Audit
  uploaded_by     INT           NULL,
  FOREIGN KEY (uploaded_by)
    REFERENCES users(user_id),
  uploaded_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ------------------------------------------------------------
-- TABLE 6: asset_audit_log
-- Records every field change made to an asset record.
-- IMMUTABLE — INSERT only. Never UPDATE or DELETE.
-- Required by Module 2 business rules.
-- References: assets, users
-- ------------------------------------------------------------
CREATE TABLE asset_audit_log (
  log_id        INT           PRIMARY KEY AUTO_INCREMENT,
  asset_id      INT           NOT NULL,
  FOREIGN KEY (asset_id)
    REFERENCES assets(asset_id),

  -- What changed
  field_name    VARCHAR(100)  NOT NULL,
    -- The column name that was changed.
    -- e.g. 'status', 'location_id', 'firmware_version'
  old_value     TEXT          NULL,
    -- The value before the change. NULL if this is a new record.
  new_value     TEXT          NULL,
    -- The value after the change.

  -- Who and when
  changed_by    INT           NULL,
    -- user_id of the person who made the change.
  FOREIGN KEY (changed_by)
    REFERENCES users(user_id),
  changed_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- Why (optional context)
  change_reason VARCHAR(255)  NULL
    -- e.g. 'Retired — end of life', 'Moved to new room'
    -- Optional. Can be left NULL.
);


-- ============================================================
-- BUSINESS RULES (enforced at application layer)
-- ============================================================
--
-- 1. asset_tag must be unique across all assets.
-- 2. serial_number must be unique per manufacturer.
--    Two assets from the same manufacturer cannot share a serial.
-- 3. An asset cannot be set to 'retired' if it has one or more
--    open (non-closed) tickets linked to it.
-- 4. location_id must be set before status can be 'active'.
-- 5. install_date cannot be a future date.
-- 6. warranty_end must be > warranty_start.
-- 7. warranty_start must be >= assets.install_date.
-- 8. bulb_hours is only applicable when the asset's category
--    has has_bulb_hours = 1. NULL for all other categories.
-- 9. parent_asset_id cannot reference the asset's own asset_id.
-- 10. Child assets inherit parent location by default,
--     but this can be overridden.
-- 11. Document uploads must be one of: pdf, jpg, jpeg, png, dwg, zip
--     Maximum file size: 50MB (51200 KB).
-- 12. Every field change on an asset record must be written
--     to asset_audit_log (old value, new value, changed_by, timestamp).
-- 13. Warranty alerts are sent at 60, 30, and 7 days before
--     warranty_end. Logic runs on application layer (cron job or
--     checked on page load).
--
-- ============================================================