<?php
// modules/reports/cron_email_report.php
// ─────────────────────────────────────────────────────
// Scheduled Report Email — Run via CRON weekly/monthly
// Command: php C:\xampp\htdocs\mtrts\modules\reports\cron_email_report.php
// ─────────────────────────────────────────────────────

if (!defined('BASE_URL')) define('BASE_URL', '/mtrts/');

require_once __DIR__ . '/../../config/db.php';
require_once __DIR__ . '/functions.php';

echo "[EMAIL REPORT] Starting at " . date('Y-m-d H:i:s') . "\n";

$end   = date('Y-m-d');
$start = date('Y-m-d', strtotime('-7 days'));

// ── 1. Gather stats ──
$sla   = get_sla_compliance_stats($pdo, $start, $end);
$mttr  = get_mttr_stats($pdo, $start, $end);
$ops   = get_operational_stats($pdo, $start, $end);
$aging = get_ticket_aging($pdo);
$esc   = get_active_escalations($pdo);

// ── 2. Build HTML email body ──
$compliance = $sla['compliance_rate'] ?? 0;
$avg_mttr   = $mttr['avg_mttr_minutes'] ? round($mttr['avg_mttr_minutes'] / 60, 1) . ' hrs' : 'N/A';
$ftfr       = $ops['ftfr_rate'] ?? 0;
$backlog    = $ops['backlog'] ?? 0;
$total      = $ops['total_tickets'] ?? 0;
$esc_count  = count($esc);

$html = <<<HTML
<html>
<head><style>
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #333; max-width: 640px; margin: 0 auto; }
    .header { background: #1a5c2a; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
    .header h1 { margin: 0; font-size: 20px; }
    .body { padding: 20px; background: #f9fafb; border: 1px solid #e5e7eb; }
    .stat-grid { display: flex; flex-wrap: wrap; gap: 12px; margin: 16px 0; }
    .stat { background: white; border: 1px solid #e5e7eb; border-radius: 8px; padding: 14px 18px; flex: 1; min-width: 120px; }
    .stat .label { font-size: 11px; color: #6b7280; text-transform: uppercase; font-weight: 700; letter-spacing: 0.5px; }
    .stat .value { font-size: 26px; font-weight: 800; color: #1a5c2a; margin-top: 4px; }
    .stat .value.red { color: #dc2626; }
    .alert { background: #fef2f2; border: 1px solid #fecaca; border-radius: 8px; padding: 12px 16px; margin: 12px 0; }
    .footer { padding: 16px; text-align: center; font-size: 11px; color: #9ca3af; }
</style></head>
<body>
    <div class="header">
        <h1>📊 MTRTS Weekly SLA Report</h1>
        <p style="margin:4px 0 0;opacity:0.8;font-size:13px;">{$start} — {$end}</p>
    </div>
    <div class="body">
        <div class="stat-grid">
            <div class="stat"><div class="label">Total Tickets</div><div class="value">{$total}</div></div>
            <div class="stat"><div class="label">SLA Compliance</div><div class="value">{$compliance}%</div></div>
            <div class="stat"><div class="label">Avg MTTR</div><div class="value">{$avg_mttr}</div></div>
            <div class="stat"><div class="label">FTFR</div><div class="value">{$ftfr}%</div></div>
            <div class="stat"><div class="label">Backlog</div><div class="value red">{$backlog}</div></div>
        </div>
HTML;

if ($esc_count > 0) {
    $html .= '<div class="alert"><strong>⚠ ' . $esc_count . ' Active Escalation(s)</strong> — Tickets have breached SLA and require management attention.</div>';
}

if ($aging) {
    $html .= '<p style="font-size:13px;color:#6b7280;margin-top:16px;">Ticket Aging: <strong>' . ($aging['bucket_0_7'] ?? 0) . '</strong> (0-7d), <strong>' . ($aging['bucket_8_14'] ?? 0) . '</strong> (8-14d), <strong>' . ($aging['bucket_15_30'] ?? 0) . '</strong> (15-30d), <strong>' . ($aging['bucket_over_30'] ?? 0) . '</strong> (30d+)</p>';
}

$html .= <<<HTML
    </div>
    <div class="footer">
        Generated by MTRTS — Media Technology Repair Tracker System<br>
        <a href="http://localhost/mtrts/modules/reports/index.php">View Full Dashboard →</a>
    </div>
</body>
</html>
HTML;

// ── 3. Send to managers ──
$recipients = $pdo->query("SELECT email, full_name FROM users WHERE role_id IN (1, 2, 8) AND is_active = 1")->fetchAll();

if (function_exists('mail')) {
    $subject = "MTRTS Weekly SLA Report — {$start} to {$end}";
    $headers  = "MIME-Version: 1.0\r\n";
    $headers .= "Content-type: text/html; charset=UTF-8\r\n";
    $headers .= "From: MTRTS System <noreply@olfu.edu.ph>\r\n";

    foreach ($recipients as $r) {
        if (mail($r['email'], $subject, $html, $headers)) {
            echo "[EMAIL REPORT] Sent to {$r['full_name']} ({$r['email']})\n";
        } else {
            echo "[EMAIL REPORT] FAILED: {$r['email']}\n";
        }
    }
} else {
    echo "[EMAIL REPORT] mail() not available. Saving report to file instead.\n";
    $path = __DIR__ . '/../../public/reports/';
    if (!is_dir($path)) mkdir($path, 0777, true);
    file_put_contents($path . 'weekly_report_' . $end . '.html', $html);
    echo "[EMAIL REPORT] Report saved to {$path}weekly_report_{$end}.html\n";
}

echo "[EMAIL REPORT] Completed at " . date('Y-m-d H:i:s') . "\n";
